Format type UI
bmlt-enabled/bmlt-root-server pull request #901
Opened 2023-05-22 12:54 UTC by otrok7

2023-05-26 20:33 UTC, jbraswell requested changes
Aside from the comments I left, my only real request is to choose a name for the new column other than "api key". I understand why you chose that name, but I find it confusing, because an "api key" is usually a type of authentication credentials for an API.

After those small changes, I'm okay with merging this.

2023-05-26 20:33 UTC, jbraswell commented on src/app/Repositories/FormatRepository.php
> +            ->where('lang_enum', 'en')
Did you mean to pass $lang here?

2023-05-26 20:33 UTC, jbraswell commented on src/tests/Unit/FormatTypesTest.php
> +        $this->assertTrue(true);
Should this file be removed? Or are you still working on it?

2023-05-26 20:33 UTC, jbraswell commented on src/tests/Feature/GetServiceBodiesTest.php
> +                'url' => $item->uri_string ?? '',
Why did this change?

2023-05-26 20:35 UTC, jbraswell commented on docker/sample-bmlt-schema.sql
> +DROP TABLE IF EXISTS `na_comdef_format_types`;
I don't think this schema file should be modified. The new database migrations should take over and create the new table.

2023-05-27 12:01 UTC, otrok7 commented
Thanks for the review, and for catching the bug.  I changed api_key to api_enum, hope that is OK.  Can you have a look at why the tests are not running.  Locally, everything is fine, and the message is not helpful.  It says the file name doesn't match with the class name, but it does.  I need another set of eyes on this.

2023-05-27 12:28 UTC, jbraswell commented
> Thanks for the review, and for catching the bug.  I changed api_key to api_enum, hope that is OK.  Can you have a look at why the tests are not running.  Locally, everything is fine, and the message is not helpful.  It says the file name doesn't match with the class name, but it does.  I need another set of eyes on this.

The name api_enum seems fine, and sure, I'll take a look at the tests. Might be a day or two - busy weekend.

2023-05-27 14:00 UTC, pjaudiomv commented
somethings causing phpunit to crash from the last commit maybe in this diff https://github.com/bmlt-enabled/bmlt-root-server/compare/45abec92064fdd25883c230f56f6089b71d3055f...e9dfe714acf42cb1e16786b916fc491d5507c3a8 error messaging is less than ideal but think the file name error is a red herring

2023-05-27 15:03 UTC, jbraswell approved these changes

2023-05-27 15:21 UTC, pjaudiomv reviewed
can we update the changelog

2023-05-27 15:31 UTC, jbraswell approved these changes

2023-05-27 15:35 UTC, pjaudiomv approved these changes

2023-05-27 15:48 UTC, merged